"""Created Sharing Model

Revision ID: 5c60127c4815
Revises: cfcf8ced52f1
Create Date: 2026-03-24 18:10:52.147203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c60127c4815'
down_revision = 'cfcf8ced52f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('sharer_id', sa.Integer(), nullable=False),
    sa.Column('sharee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['sharee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sharer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_recipe')
    # ### end Alembic commands ###
